//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendingDataExtractor
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class VendingBackEndEntities : DbContext
    {
        public VendingBackEndEntities()
            : base("name=VendingBackEndEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Entity1> Entity1 { get; set; }
    
        public virtual ObjectResult<Get_SalesEntry_All_Result> Get_SalesEntry_All()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_SalesEntry_All_Result>("Get_SalesEntry_All");
        }
    }
}
