//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
//[DataContract(Namespace = "http://api.unleashedsoftware.com/version/1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://api.unleashedsoftware.com/version/1")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://api.unleashedsoftware.com/version/1", IsNullable = false)]
public partial class Products {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Pagination", typeof(ProductsPagination))]
    [System.Xml.Serialization.XmlElementAttribute("Product", typeof(ProductsProduct))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://api.unleashedsoftware.com/version/1")]
public partial class ProductsPagination {
    
    private string numberOfItemsField;
    
    private string pageSizeField;
    
    private string pageNumberField;
    
    private string numberOfPagesField;
    
    /// <remarks/>
    public string NumberOfItems {
        get {
            return this.numberOfItemsField;
        }
        set {
            this.numberOfItemsField = value;
        }
    }
    
    /// <remarks/>
    public string PageSize {
        get {
            return this.pageSizeField;
        }
        set {
            this.pageSizeField = value;
        }
    }
    
    /// <remarks/>
    public string PageNumber {
        get {
            return this.pageNumberField;
        }
        set {
            this.pageNumberField = value;
        }
    }
    
    /// <remarks/>
    public string NumberOfPages {
        get {
            return this.numberOfPagesField;
        }
        set {
            this.numberOfPagesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://api.unleashedsoftware.com/version/1")]
public partial class ProductsProduct {
    
    private string guidField;
    
    private string lastModifiedOnField;
    
    private string productCodeField;
    
    private string productDescriptionField;
    
    private string packSizeField;
    
    private string widthField;
    
    private string heightField;
    
    private string depthField;
    
    private string weightField;
    
    private string minStockAlertLevelField;
    
    private string maxStockAlertLevelField;
    
    private string reOrderPointField;
    
    private string neverDiminishingField;
    
    private string lastCostField;
    
    private string defaultPurchasePriceField;
    
    private string defaultSellPriceField;
    
    private string averageLandPriceField;
    
    private string obsoleteField;
    
    private string xeroTaxRateField;
    
    private string taxablePurchaseField;
    
    private string taxableSalesField;
    
    private string xeroSalesTaxRateField;
    
    private string isComponentField;
    
    private string isAssembledProductField;
    
    private string canAutoAssembleField;
    
    private string createdByField;
    
    private ProductsProductSellPriceTier1[] sellPriceTier1Field;
    
    private ProductsProductSellPriceTier2[] sellPriceTier2Field;
    
    private ProductsProductSellPriceTier3[] sellPriceTier3Field;
    
    private ProductsProductSellPriceTier4[] sellPriceTier4Field;
    
    private ProductsProductSellPriceTier5[] sellPriceTier5Field;
    
    private ProductsProductSellPriceTier6[] sellPriceTier6Field;
    
    private ProductsProductSellPriceTier7[] sellPriceTier7Field;
    
    private ProductsProductSellPriceTier8[] sellPriceTier8Field;
    
    private ProductsProductSellPriceTier9[] sellPriceTier9Field;
    
    private ProductsProductSellPriceTier10[] sellPriceTier10Field;
    
    /// <remarks/>
    public string Guid {
        get {
            return this.guidField;
        }
        set {
            this.guidField = value;
        }
    }
    
    /// <remarks/>
    public string LastModifiedOn {
        get {
            return this.lastModifiedOnField;
        }
        set {
            this.lastModifiedOnField = value;
        }
    }
    
    /// <remarks/>
    public string ProductCode {
        get {
            return this.productCodeField;
        }
        set {
            this.productCodeField = value;
        }
    }
    
    /// <remarks/>
    public string ProductDescription {
        get {
            return this.productDescriptionField;
        }
        set {
            this.productDescriptionField = value;
        }
    }
    
    /// <remarks/>
    public string PackSize {
        get {
            return this.packSizeField;
        }
        set {
            this.packSizeField = value;
        }
    }
    
    /// <remarks/>
    public string Width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    public string Height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    public string Depth {
        get {
            return this.depthField;
        }
        set {
            this.depthField = value;
        }
    }
    
    /// <remarks/>
    public string Weight {
        get {
            return this.weightField;
        }
        set {
            this.weightField = value;
        }
    }
    
    /// <remarks/>
    public string MinStockAlertLevel {
        get {
            return this.minStockAlertLevelField;
        }
        set {
            this.minStockAlertLevelField = value;
        }
    }
    
    /// <remarks/>
    public string MaxStockAlertLevel {
        get {
            return this.maxStockAlertLevelField;
        }
        set {
            this.maxStockAlertLevelField = value;
        }
    }
    
    /// <remarks/>
    public string ReOrderPoint {
        get {
            return this.reOrderPointField;
        }
        set {
            this.reOrderPointField = value;
        }
    }
    
    /// <remarks/>
    public string NeverDiminishing {
        get {
            return this.neverDiminishingField;
        }
        set {
            this.neverDiminishingField = value;
        }
    }
    
    /// <remarks/>
    public string LastCost {
        get {
            return this.lastCostField;
        }
        set {
            this.lastCostField = value;
        }
    }
    
    /// <remarks/>
    public string DefaultPurchasePrice {
        get {
            return this.defaultPurchasePriceField;
        }
        set {
            this.defaultPurchasePriceField = value;
        }
    }
    
    /// <remarks/>
    public string DefaultSellPrice {
        get {
            return this.defaultSellPriceField;
        }
        set {
            this.defaultSellPriceField = value;
        }
    }
    
    /// <remarks/>
    public string AverageLandPrice {
        get {
            return this.averageLandPriceField;
        }
        set {
            this.averageLandPriceField = value;
        }
    }
    
    /// <remarks/>
    public string Obsolete {
        get {
            return this.obsoleteField;
        }
        set {
            this.obsoleteField = value;
        }
    }
    
    /// <remarks/>
    public string XeroTaxRate {
        get {
            return this.xeroTaxRateField;
        }
        set {
            this.xeroTaxRateField = value;
        }
    }
    
    /// <remarks/>
    public string TaxablePurchase {
        get {
            return this.taxablePurchaseField;
        }
        set {
            this.taxablePurchaseField = value;
        }
    }
    
    /// <remarks/>
    public string TaxableSales {
        get {
            return this.taxableSalesField;
        }
        set {
            this.taxableSalesField = value;
        }
    }
    
    /// <remarks/>
    public string XeroSalesTaxRate {
        get {
            return this.xeroSalesTaxRateField;
        }
        set {
            this.xeroSalesTaxRateField = value;
        }
    }
    
    /// <remarks/>
    public string IsComponent {
        get {
            return this.isComponentField;
        }
        set {
            this.isComponentField = value;
        }
    }
    
    /// <remarks/>
    public string IsAssembledProduct {
        get {
            return this.isAssembledProductField;
        }
        set {
            this.isAssembledProductField = value;
        }
    }
    
    /// <remarks/>
    public string CanAutoAssemble {
        get {
            return this.canAutoAssembleField;
        }
        set {
            this.canAutoAssembleField = value;
        }
    }
    
    /// <remarks/>
    public string CreatedBy {
        get {
            return this.createdByField;
        }
        set {
            this.createdByField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SellPriceTier1")]
    public ProductsProductSellPriceTier1[] SellPriceTier1 {
        get {
            return this.sellPriceTier1Field;
        }
        set {
            this.sellPriceTier1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SellPriceTier2")]
    public ProductsProductSellPriceTier2[] SellPriceTier2 {
        get {
            return this.sellPriceTier2Field;
        }
        set {
            this.sellPriceTier2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SellPriceTier3")]
    public ProductsProductSellPriceTier3[] SellPriceTier3 {
        get {
            return this.sellPriceTier3Field;
        }
        set {
            this.sellPriceTier3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SellPriceTier4")]
    public ProductsProductSellPriceTier4[] SellPriceTier4 {
        get {
            return this.sellPriceTier4Field;
        }
        set {
            this.sellPriceTier4Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SellPriceTier5")]
    public ProductsProductSellPriceTier5[] SellPriceTier5 {
        get {
            return this.sellPriceTier5Field;
        }
        set {
            this.sellPriceTier5Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SellPriceTier6")]
    public ProductsProductSellPriceTier6[] SellPriceTier6 {
        get {
            return this.sellPriceTier6Field;
        }
        set {
            this.sellPriceTier6Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SellPriceTier7")]
    public ProductsProductSellPriceTier7[] SellPriceTier7 {
        get {
            return this.sellPriceTier7Field;
        }
        set {
            this.sellPriceTier7Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SellPriceTier8")]
    public ProductsProductSellPriceTier8[] SellPriceTier8 {
        get {
            return this.sellPriceTier8Field;
        }
        set {
            this.sellPriceTier8Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SellPriceTier9")]
    public ProductsProductSellPriceTier9[] SellPriceTier9 {
        get {
            return this.sellPriceTier9Field;
        }
        set {
            this.sellPriceTier9Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SellPriceTier10")]
    public ProductsProductSellPriceTier10[] SellPriceTier10 {
        get {
            return this.sellPriceTier10Field;
        }
        set {
            this.sellPriceTier10Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://api.unleashedsoftware.com/version/1")]
public partial class ProductsProductSellPriceTier1 {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://api.unleashedsoftware.com/version/1")]
public partial class ProductsProductSellPriceTier2 {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://api.unleashedsoftware.com/version/1")]
public partial class ProductsProductSellPriceTier3 {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://api.unleashedsoftware.com/version/1")]
public partial class ProductsProductSellPriceTier4 {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://api.unleashedsoftware.com/version/1")]
public partial class ProductsProductSellPriceTier5 {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://api.unleashedsoftware.com/version/1")]
public partial class ProductsProductSellPriceTier6 {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://api.unleashedsoftware.com/version/1")]
public partial class ProductsProductSellPriceTier7 {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://api.unleashedsoftware.com/version/1")]
public partial class ProductsProductSellPriceTier8 {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://api.unleashedsoftware.com/version/1")]
public partial class ProductsProductSellPriceTier9 {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://api.unleashedsoftware.com/version/1")]
public partial class ProductsProductSellPriceTier10 {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}
