//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[KnownTypeAttribute(typeof(SalesOrder))]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://api.unleashedsoftware.com/version/1")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://api.unleashedsoftware.com/version/1", IsNullable=false)]
public partial class SalesOrder {
    
    private string guidField;
    
    private string lastModifiedOnField;
    
    private string orderNumberField;
    
    private string orderDateField;
    
    private string requiredDateField;
    
    private string orderStatusField;
    
    private string receivedDateField;
    
    private string exchangeRateField;
    
    private string discountRateField;
    
    private string taxRateField;
    
    private string xeroTaxCodeField;
    
    private string subTotalField;
    
    private string taxTotalField;
    
    private string totalField;
    
    private string totalVolumeField;
    
    private string totalWeightField;
    
    private string bCSubTotalField;
    
    private string bCTaxTotalField;
    
    private string bCTotalField;
    
    private string paymentDueDateField;
    
    private string sendAccountingJournalOnlyField;
    
    private SalesOrderCustomer[] customerField;
    
    private SalesOrderTax[] taxField;
    
    private SalesOrderSalesOrderLinesSalesOrderLine[] salesOrderLinesField;
    
    /// <remarks/>
    public string Guid {
        get {
            return this.guidField;
        }
        set {
            this.guidField = value;
        }
    }
    
    /// <remarks/>
    public string LastModifiedOn {
        get {
            return this.lastModifiedOnField;
        }
        set {
            this.lastModifiedOnField = value;
        }
    }
    
    /// <remarks/>
    public string OrderNumber {
        get {
            return this.orderNumberField;
        }
        set {
            this.orderNumberField = value;
        }
    }
    
    /// <remarks/>
    public string OrderDate {
        get {
            return this.orderDateField;
        }
        set {
            this.orderDateField = value;
        }
    }
    
    /// <remarks/>
    public string RequiredDate {
        get {
            return this.requiredDateField;
        }
        set {
            this.requiredDateField = value;
        }
    }
    
    /// <remarks/>
    public string OrderStatus {
        get {
            return this.orderStatusField;
        }
        set {
            this.orderStatusField = value;
        }
    }
    
    /// <remarks/>
    public string ReceivedDate {
        get {
            return this.receivedDateField;
        }
        set {
            this.receivedDateField = value;
        }
    }
    
    /// <remarks/>
    public string ExchangeRate {
        get {
            return this.exchangeRateField;
        }
        set {
            this.exchangeRateField = value;
        }
    }
    
    /// <remarks/>
    public string DiscountRate {
        get {
            return this.discountRateField;
        }
        set {
            this.discountRateField = value;
        }
    }
    
    /// <remarks/>
    public string TaxRate {
        get {
            return this.taxRateField;
        }
        set {
            this.taxRateField = value;
        }
    }
    
    /// <remarks/>
    public string XeroTaxCode {
        get {
            return this.xeroTaxCodeField;
        }
        set {
            this.xeroTaxCodeField = value;
        }
    }
    
    /// <remarks/>
    public string SubTotal {
        get {
            return this.subTotalField;
        }
        set {
            this.subTotalField = value;
        }
    }
    
    /// <remarks/>
    public string TaxTotal {
        get {
            return this.taxTotalField;
        }
        set {
            this.taxTotalField = value;
        }
    }
    
    /// <remarks/>
    public string Total {
        get {
            return this.totalField;
        }
        set {
            this.totalField = value;
        }
    }
    
    /// <remarks/>
    public string TotalVolume {
        get {
            return this.totalVolumeField;
        }
        set {
            this.totalVolumeField = value;
        }
    }
    
    /// <remarks/>
    public string TotalWeight {
        get {
            return this.totalWeightField;
        }
        set {
            this.totalWeightField = value;
        }
    }
    
    /// <remarks/>
    public string BCSubTotal {
        get {
            return this.bCSubTotalField;
        }
        set {
            this.bCSubTotalField = value;
        }
    }
    
    /// <remarks/>
    public string BCTaxTotal {
        get {
            return this.bCTaxTotalField;
        }
        set {
            this.bCTaxTotalField = value;
        }
    }
    
    /// <remarks/>
    public string BCTotal {
        get {
            return this.bCTotalField;
        }
        set {
            this.bCTotalField = value;
        }
    }
    
    /// <remarks/>
    public string PaymentDueDate {
        get {
            return this.paymentDueDateField;
        }
        set {
            this.paymentDueDateField = value;
        }
    }
    
    /// <remarks/>
    public string SendAccountingJournalOnly {
        get {
            return this.sendAccountingJournalOnlyField;
        }
        set {
            this.sendAccountingJournalOnlyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Customer")]
    public SalesOrderCustomer[] Customer {
        get {
            return this.customerField;
        }
        set {
            this.customerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Tax")]
    public SalesOrderTax[] Tax {
        get {
            return this.taxField;
        }
        set {
            this.taxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("SalesOrderLine", typeof(SalesOrderSalesOrderLinesSalesOrderLine), IsNullable=false)]
    public SalesOrderSalesOrderLinesSalesOrderLine[] SalesOrderLines {
        get {
            return this.salesOrderLinesField;
        }
        set {
            this.salesOrderLinesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[DataContract]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://api.unleashedsoftware.com/version/1")]
public partial class SalesOrderCustomer {
    
    private string guidField;
    
    private string lastModifiedOnField;
    
    private string customerCodeField;
    
    /// <remarks/>
    public string Guid {
        get {
            return this.guidField;
        }
        set {
            this.guidField = value;
        }
    }
    
    /// <remarks/>
    public string LastModifiedOn {
        get {
            return this.lastModifiedOnField;
        }
        set {
            this.lastModifiedOnField = value;
        }
    }
    
    /// <remarks/>
    public string CustomerCode {
        get {
            return this.customerCodeField;
        }
        set {
            this.customerCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[DataContract]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://api.unleashedsoftware.com/version/1")]
public partial class SalesOrderTax {
    
    private string guidField;
    
    private string lastModifiedOnField;
    
    private string taxCodeField;
    
    private string taxRateField;
    
    private string canApplyToExpensesField;
    
    private string canApplyToRevenueField;
    
    /// <remarks/>
    public string Guid {
        get {
            return this.guidField;
        }
        set {
            this.guidField = value;
        }
    }
    
    /// <remarks/>
    public string LastModifiedOn {
        get {
            return this.lastModifiedOnField;
        }
        set {
            this.lastModifiedOnField = value;
        }
    }
    
    /// <remarks/>
    public string TaxCode {
        get {
            return this.taxCodeField;
        }
        set {
            this.taxCodeField = value;
        }
    }
    
    /// <remarks/>
    public string TaxRate {
        get {
            return this.taxRateField;
        }
        set {
            this.taxRateField = value;
        }
    }
    
    /// <remarks/>
    public string CanApplyToExpenses {
        get {
            return this.canApplyToExpensesField;
        }
        set {
            this.canApplyToExpensesField = value;
        }
    }
    
    /// <remarks/>
    public string CanApplyToRevenue {
        get {
            return this.canApplyToRevenueField;
        }
        set {
            this.canApplyToRevenueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[DataContract]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://api.unleashedsoftware.com/version/1")]
public partial class SalesOrderSalesOrderLinesSalesOrderLine {
    
    private string guidField;
    
    private string lastModifiedOnField;
    
    private string lineNumberField;
    
    private string dueDateField;
    
    private string orderQuantityField;
    
    private string unitPriceField;
    
    private string discountRateField;
    
    private string lineTotalField;
    
    private string volumeField;
    
    private string weightField;
    
    private string unitCostField;
    
    private string taxRateField;
    
    private string lineTaxField;
    
    private string xeroTaxCodeField;
    
    private string bCUnitPriceField;
    
    private string bCLineTotalField;
    
    private string bCLineTaxField;
    
    private SalesOrderSalesOrderLinesSalesOrderLineProduct[] productField;
    
    /// <remarks/>
    public string Guid {
        get {
            return this.guidField;
        }
        set {
            this.guidField = value;
        }
    }
    
    /// <remarks/>
    public string LastModifiedOn {
        get {
            return this.lastModifiedOnField;
        }
        set {
            this.lastModifiedOnField = value;
        }
    }
    
    /// <remarks/>
    public string LineNumber {
        get {
            return this.lineNumberField;
        }
        set {
            this.lineNumberField = value;
        }
    }
    
    /// <remarks/>
    public string DueDate {
        get {
            return this.dueDateField;
        }
        set {
            this.dueDateField = value;
        }
    }
    
    /// <remarks/>
    public string OrderQuantity {
        get {
            return this.orderQuantityField;
        }
        set {
            this.orderQuantityField = value;
        }
    }
    
    /// <remarks/>
    public string UnitPrice {
        get {
            return this.unitPriceField;
        }
        set {
            this.unitPriceField = value;
        }
    }
    
    /// <remarks/>
    public string DiscountRate {
        get {
            return this.discountRateField;
        }
        set {
            this.discountRateField = value;
        }
    }
    
    /// <remarks/>
    public string LineTotal {
        get {
            return this.lineTotalField;
        }
        set {
            this.lineTotalField = value;
        }
    }
    
    /// <remarks/>
    public string Volume {
        get {
            return this.volumeField;
        }
        set {
            this.volumeField = value;
        }
    }
    
    /// <remarks/>
    public string Weight {
        get {
            return this.weightField;
        }
        set {
            this.weightField = value;
        }
    }
    
    /// <remarks/>
    public string UnitCost {
        get {
            return this.unitCostField;
        }
        set {
            this.unitCostField = value;
        }
    }
    
    /// <remarks/>
    public string TaxRate {
        get {
            return this.taxRateField;
        }
        set {
            this.taxRateField = value;
        }
    }
    
    /// <remarks/>
    public string LineTax {
        get {
            return this.lineTaxField;
        }
        set {
            this.lineTaxField = value;
        }
    }
    
    /// <remarks/>
    public string XeroTaxCode {
        get {
            return this.xeroTaxCodeField;
        }
        set {
            this.xeroTaxCodeField = value;
        }
    }
    
    /// <remarks/>
    public string BCUnitPrice {
        get {
            return this.bCUnitPriceField;
        }
        set {
            this.bCUnitPriceField = value;
        }
    }
    
    /// <remarks/>
    public string BCLineTotal {
        get {
            return this.bCLineTotalField;
        }
        set {
            this.bCLineTotalField = value;
        }
    }
    
    /// <remarks/>
    public string BCLineTax {
        get {
            return this.bCLineTaxField;
        }
        set {
            this.bCLineTaxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Product")]
    public SalesOrderSalesOrderLinesSalesOrderLineProduct[] Product {
        get {
            return this.productField;
        }
        set {
            this.productField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[DataContract]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://api.unleashedsoftware.com/version/1")]
public partial class SalesOrderSalesOrderLinesSalesOrderLineProduct {
    
    private string guidField;
    
    private string productCodeField;
    
    /// <remarks/>
    public string Guid {
        get {
            return this.guidField;
        }
        set {
            this.guidField = value;
        }
    }
    
    /// <remarks/>
    public string ProductCode {
        get {
            return this.productCodeField;
        }
        set {
            this.productCodeField = value;
        }
    }
}

